language: ruby
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem update --system
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
